name: Deploy test (staging)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure (staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: fluxorbit-ae
          slot-name: staging
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGING }}
          package: .
